### ISSUE TITLE
Windows finds CoinMiner in Desktop-Installer

### ISSUE THREAD

**Issue by penCsharpener** [loki-project/session-desktop#1187] opened 2020-06-20 14:37 UTC
**Describe the bug**
Windows reports Session Desktop installer as having a CoinMiner.

**To Reproduce**
Windows 2004 latest patch level (19041.329)

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/26190934/85204345-3057ce00-b314-11ea-9e6d-447868b57dee.png)

**Other information (please complete the following information):**

* Device: Desktop PC
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash: 1.0.4 through to 1.0.9

**Comment by D3191** [comment] 2020-06-21 18:03
This is a duplicate of https://github.com/loki-project/session-desktop/issues/1149

**Closed** 2020-06-22 06:34 UTC
