### ISSUE TITLE
Clicking "Accept" on friend request does nothing

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#914] opened 2020-02-24 00:47 UTC
**Describe the bug**
![Screen Shot 2020-02-23 at 4 51 35 PM](https://user-images.githubusercontent.com/1224671/75123501-cb89b100-565c-11ea-9210-41e39d46b90e.png)

when accepting multiple friend requests the UI gets stuck in a state where clicking decline or accept does nothing.

Saw this in 1.0.2 but also getting it in the latest clearnet, tracked an exception this time:

`No identity record for ${number}` exception throw in `getVerified` in signal_protocol_store.js

On further testing, the exception maybe unrelate. I'm still getting the behavior with no exceptions.

**To Reproduce**
Haven't made a persistent repro case, maybe relate to app data or corrupt multidevice

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

```
INFO  2020-02-24T00:43:05.810Z startLongPolling for 3 connections
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.811Z Start idle detector
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.811Z swarmNodes 5 for 053ade5e17a85b1aa48d394f5ad7e27f17c7bd7c4f711e47ef8f8f3faa8065cb46
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.812Z 0 195.181.246.58:22021
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.813Z 1 91.121.132.120:23031
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.814Z 2 104.244.74.251:22021
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.814Z 3 51.91.248.129:22021
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.814Z 4 207.201.218.211:22021
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.815Z There are currently 5 swarmNodes for pubKey in our local database
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:05.898Z getAllFromCache loaded 0 saved envelopes
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:06.242Z LokiAppDotNetAPI registered server https://chat.getsession.org
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:06.502Z set token I7cxbX2tKmgXwn1d9Q3N6ETELQpnw3Ui5bPqtGfZWoMVY9bpg0j8WPGxiKXfOXKIJryQKsvuij5BXDaHxxl1SN3o7w6JxLpe for https://chat.getsession.org
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:06.770Z registered LokiPublicChannel 1 on https://chat.getsession.org
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:06.770Z LokiPublicChannel open 1 on https://chat.getsession.org
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:06.777Z LokiPublicChannelAPI started for 1 on https://chat.getsession.org
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:10.969Z Upgrade message schema (with index): {done: true, numProcessed: 0, fetchDuration: 2, upgradeDuration: 0, saveDuration: 0, …}
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:10.972Z Background migration complete. Stopping idle detector.
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:10.973Z Stop idle detector
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:28.026Z Remove all notifications
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:29.028Z Update notifications: {shouldClearNotifications: false, shouldPlayNotificationSound: false, shouldShowNotifications: false, type: "disabled", isNotificationGroupingSupported: true}
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:32.449Z open inbox
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:32.473Z fetchMessages
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 WARN  2020-02-24T00:43:32.582Z Failed to fetch contact prekey: 053ade5e17a85b1aa48d394f5ad7e27f17c7bd7c4f711e47ef8f8f3faa8065cb46
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 WARN  2020-02-24T00:43:32.583Z Failed to fetch contact signed prekey: 053ade5e17a85b1aa48d394f5ad7e27f17c7bd7c4f711e47ef8f8f3faa8065cb46
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:32.604Z thisDeviceMessageType outgoing
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:32.610Z Conversation 055e5d248aacbf5ae4f08b5f0a7f9193301ab4c263c160f6dec2bd701939d8ff09 took 132 milliseconds to load
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:32.644Z Sending 1 read receipts
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:32.794Z Worker job 1 (calcPoW) succeeded in 37ms
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.003Z open inbox
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.021Z fetchMessages
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 WARN  2020-02-24T00:43:50.032Z Failed to fetch contact prekey: 053ade5e17a85b1aa48d394f5ad7e27f17c7bd7c4f711e47ef8f8f3faa8065cb46
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 WARN  2020-02-24T00:43:50.033Z Failed to fetch contact signed prekey: 053ade5e17a85b1aa48d394f5ad7e27f17c7bd7c4f711e47ef8f8f3faa8065cb46
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.044Z Successful storage message to 056606cf8b7d0e6228f55d61c348874b6496c8432504a53b5b040c8f6f1a99992f
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.051Z Conversation 05621b90cfa59b1989e01aa510b7a6c103a2f6a6002165a409a812613220738106 took 28 milliseconds to load
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.056Z thisDeviceMessageType outgoing
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.079Z device registrationId 0!
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.081Z isTrustedForSending: No previous record, returning true...
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.112Z Sending 1 read receipts
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.227Z Saving new identity...
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.234Z thisDeviceMessageType onlineBroadcast
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.357Z Worker job 2 (calcPoW) succeeded in 145ms
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.407Z Worker job 3 (calcPoW) succeeded in 133ms
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.565Z device registrationId 0!
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.565Z isTrustedForSending: No previous record, returning true...
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.632Z Saving new identity...
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.640Z thisDeviceMessageType onlineBroadcast
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:50.726Z Worker job 4 (calcPoW) succeeded in 50ms
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:51.242Z Successful storage message to 055e5d248aacbf5ae4f08b5f0a7f9193301ab4c263c160f6dec2bd701939d8ff09
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:51.333Z Successful storage message to 056606cf8b7d0e6228f55d61c348874b6496c8432504a53b5b040c8f6f1a99992f
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:51.482Z Remove all notifications
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:51.720Z Successful storage message to 05621b90cfa59b1989e01aa510b7a6c103a2f6a6002165a409a812613220738106
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:43:52.485Z Update notifications: {shouldClearNotifications: false, shouldPlayNotificationSound: false, shouldShowNotifications: false, type: "disabled", isNotificationGroupingSupported: true}
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:45:03.043Z Remove all notifications
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:45:04.049Z Update notifications: {shouldClearNotifications: false, shouldPlayNotificationSound: false, shouldShowNotifications: false, type: "disabled", isNotificationGroupingSupported: true}
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 ERROR 2020-02-24T00:45:16.355Z lokiRpc sendToProxy snode 45.153.186.104:22021 error Service node is not ready: not in any swarm; not done syncing; 

/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:45:44.918Z Remove all notifications
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:45:45.919Z Update notifications: {shouldClearNotifications: false, shouldPlayNotificationSound: false, shouldShowNotifications: false, type: "disabled", isNotificationGroupingSupported: true}
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:47:44.593Z Remove all notifications
/Users/rtharp/Sites/lm-n-fileproxy/js/logging.js:114 INFO  2020-02-24T00:47:45.598Z Update notifications: {shouldClearNotifications: false, shouldPlayNotificationSound: false, shouldShowNotifications: false, type: "disabled", isNotificationGroupingSupported: true}
```

**Other information (please complete the following information):**

* Device: Mac
* OS: 10.14
* Session Version or Git commit hash: c1b115463f044c87e92225e1591a53785ae4fbcd

**Comment by konstantinullrich** [comment] 2020-03-02 11:08
Hi,
I'll take a look.

**Comment by konstantinullrich** [comment] 2020-03-02 14:40
Hi @neuroscr, does this error still appear? Because I couldn't reproduce the error on my machine.

**Comment by KeeJef** [comment] 2020-03-05 00:42
To reproduce you just need 2 people to send you a friend request at the same time, you will be able to accept one, but the other friend request you will be unable to accept

**Comment by konstantinullrich** [comment] 2020-03-05 06:08
I tried to reproduce it this way, but I wasn't able to.

**Comment by neuroscr** [comment] 2020-03-05 07:35
Yea, I still have it with a single contact. I think it maybe a data/state bug with this specific contact. Marking this low priority until someone else reports it but it is still happening in my dev copy, will close if it eventually stops.

**Comment by KeeJef** [comment] 2020-03-05 07:41
Its not low because it can prevent two users from talking to each other since the friend request cannot be accepted, ill try and reproduce tonight

**Comment by konstantinullrich** [comment] 2020-03-08 17:30
@KeeJef Where you able to reproduce this bug?

**Comment by KeeJef** [comment] 2020-03-10 05:04
i couldn't reproduce how i got into this state, but my client has the same issue. Will leave this here until someone can come up with a reproducible report

**Comment by Bilb** [comment] 2020-03-26 05:55
Do you have more than just the friend request in the conversation with this issue?

**Comment by Brice-W** [comment] 2020-04-29 05:44
I've had that issue as well, and finally found a scenario to reproduce it:
Starting with a Desktop device A1 and a secondary device A2 that can be either Desktop or Android.
B is an other Desktop device that isn’t friend with A1/A2.
When A1 and A2 are linked, send a friend request to B with A2. When the request arrives in B, it is not possible to click on Accept and Decline buttons.

**Comment by Bilb** [comment] 2020-09-11 01:30
Closing as we no longer have friend request logic

**Closed by Bilb** 2020-09-11 01:30 UTC
Labels: Low, bug
