### ISSUE TITLE
v1.1.0 issue when re-start

### ISSUE THREAD

**Issue by danrobi11** [loki-project/session-desktop#1257] opened 2020-07-16 21:24 UTC
Hello
Im running linux (mx linux)
I've tried the deb file , flatpak and appimage
They all have same issue here.
When re-starting session just get stuck at main screen, nothing I can do 

Also flatpak version dont seems to properly close.
Or theres an invisible systray and it close to tray. I dont know, I dont see any session icon in tray.
But I have to kill the PID to properly shut it down

**Comment by Bilb** [comment] 2020-07-16 22:41
Hi,
I cannot reproduce this issue on Ubuntu 20.04. Can you give me the MX Linux you are running on so I can give it a try?
Thanks

**Comment by JettScythe** [comment] 2020-07-17 01:41
Having the same issue. 
Manjaro Linux w/ 5.4.44 kernel

**Comment by danrobi11** [comment] 2020-07-17 03:00
-Version-
Kernel: Linux 4.19.0-9-amd64 (x86_64)
Version: #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07)
C Library: GNU C Library / (Debian GLIBC 2.28-10) 2.28
Distribution: Debian GNU/Linux 10 (buster)
WM: awesome

**Comment by finnishbroccoli** [comment] 2020-07-17 03:00
I have same issue, I upgraded Linux appimage from 1.0.9 to 1.1.1 and only main screen appears. It does not ask password.
Arch Linux 5.4.51-1-lts

**Comment by Mikunj** [comment] 2020-07-17 03:27
Thanks for the reports, Seems to only happen when a password is set. We'll get this fixed as soon as we can

**Comment by Mikunj** [comment] 2020-07-17 05:01
Fixed in #1260. We'll be making another release shortly.

**Closed** 2020-07-17 05:02 UTC
