### ISSUE TITLE
Feature request: Responsive "desktop" client

### ISSUE THREAD

**Issue by not-a-kiwi** [loki-project/session-desktop#1382] opened 2020-10-21 12:19 UTC
There are cases when a "desktop" build needs to run on a smaller window:
 * phones running Linux (Librem 5, PinePhone, others…)
 * small window for background chatting
 * secondary screen on a normal desktop

Telegram does this quite well. Also, this may (but not sure) be useful to share more of the code base among the platforms.

See also https://github.com/signalapp/Signal-Desktop/issues/2454

**Comment by invalid-error** [comment] 2020-12-10 07:36
Concerning, Linux phones:
Librem 5 App voting just selected Signal now (daily updated).
Maybe this is helpful and benefit for all small touch screen devices:
https://developer.puri.sm/Librem5/Apps/Guides/Design/Constraints.html
https://gitlab.gnome.org/GNOME/libhandy/

**Comment by Bilb** [comment] 2020-12-17 23:05
This is a duplicate of #1304  so we will close that one

**Closed by Bilb** 2020-12-17 23:05 UTC
