### ISSUE TITLE
Camera and microphone icons doesn't show

### ISSUE THREAD

**Issue by estatra** [loki-project/session-desktop#1116] opened 2020-05-03 19:15 UTC
**Describe the bug**
Exact same problem as in [#99](https://github.com/loki-project/session-android/issues/99) on Android.

* Device: Desktop PC
* OS: Arch Linux, Kernel 5.6.8-arch1-1

![session](https://user-images.githubusercontent.com/57003922/80923314-42c47b00-8d59-11ea-92a8-bbd624eb920f.png)

**Comment by KeeJef** [comment] 2020-05-27 06:07
Does this happen at all window sizes? What were your steps to reproduce? and which Session version were you using?

**Comment by vincentbavitz** [comment] 2020-05-27 06:11
This is due to Electron upgrade breaking the microphone input. Media permissions in settings have henceforth been disabled until this is fixed.

**Comment by cristianovitorino** [comment] 2020-05-27 06:14
> Does this happen at all window sizes?
Yes.

> What were your steps to reproduce?
1. Download the _AppImage_  from the release pages.
2. Open Session.
3. Add a friend and start a conversation.
4. Try a normal conversation.
5. Try deleting the conversation.
6 Try starting a new conversation.
7. Try deleting messages.

> [...] and which Session version were you using?
I've tried **1.0.7** and **1.0.8**.

**Comment by cristianovitorino** [comment] 2020-05-27 06:17
> This is due to Electron upgrade breaking the microphone input. Media permissions in settings have henceforth been disabled until this is fixed.

I see. Makes sense, thanks for the feedback. I check now and then and follow the development, Session seems like it's heading a great direction. Can't wait to see it mature.

**Comment by Bilb** [comment] 2020-12-10 05:54
This should be fixed on v1.4.3, please feel free to reopen if not

**Closed by Bilb** 2020-12-10 05:54 UTC
Labels: bug
