### ISSUE TITLE
Drag and Drop Attachment

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#888] opened 2020-02-20 13:08 UTC
Allow attachments to be sent by dragging the attachment into the message view

**Comment by User486375** [comment] 2020-03-26 13:32
@vincentbavitz Isn't this a duplicate of #703? Also, without having a to make another issue, could the ability to copy and paste (ctrl c ctrl v) be included in this issue? Considering both are currently possible in signals desktop client, I'm assuming it's not a hard fix.

**Comment by KeeJef** [comment] 2020-03-26 23:51
Yes, Duplicate of #703

**Closed by KeeJef** 2020-03-26 23:51 UTC
Labels: User Interface, enhancement
