### ISSUE TITLE
Segmentation fault on Fedora 31 (AppImage)

### ISSUE THREAD

**Issue by MorgothSauron** [loki-project/session-desktop#941] opened 2020-03-02 21:17 UTC
**Describe the bug**
When I start the AppImage on Fedora 31 it fails with a segmentation fault.

I tried to delete the config directory `/home/myuser/.config/Session` but it's still failinng

**To Reproduce**
- Download session-messenger-desktop-linux-1.0.2.AppImage
- Start the application

**Screenshots or Logs**
The following is logged when starting the application in a terminal
```
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.session-messenger-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /tmp/.mount_sessioNzTyx4/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
userData: /home/myuser/.config/Session
config/get: Successfully read user config file
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
{"name":"log","hostname":"hostname.home","pid":33470,"level":30,"msg":"app ready","time":"2020-03-02T21:12:33.102Z","v":0}
{"name":"log","hostname":"hostname.home","pid":33470,"level":30,"msg":"starting version 1.0.2","time":"2020-03-02T21:12:33.103Z","v":0}
{"name":"log","hostname":"hostname.home","pid":33470,"level":30,"msg":"updateSchema: Current schema version: 0; Most recent schema version: 11; SQLite version: 3.20.1; SQLCipher version: 3.4.2;","time":"2020-03-02T21:12:33.130Z","v":0}
{"name":"log","hostname":"hostname.home","pid":33470,"level":30,"msg":"updateToSchemaVersion1: starting...","time":"2020-03-02T21:12:33.131Z","v":0}
Segmentation fault (core dumped)
```

**Other information (please complete the following information):**

* Device: PC
* OS: Fedora 31
* Session Version or Git commit hash: session-messenger-desktop-linux-1.0.2.AppImage

**Comment by KeeJef** [comment] 2020-03-03 00:10
Duplicate of this #875 we are looking into this issue

**Closed by KeeJef** 2020-03-03 00:10 UTC
