### ISSUE TITLE
Invite a friend to already joined group

### ISSUE THREAD

**Issue by abenhamo** [loki-project/session-desktop#803] opened 2020-02-06 23:51 UTC
Issue: User should not be able to invite a friend to an open group, if that friend is already in the group
Obtained: 
The user is able to send the invitation
The friend received the invitation
Expected:
The user should not be able to send the invitation
The friend won't receive the invitation

**Comment by KeeJef** [comment] 2020-02-21 00:09
Closed as a duplicate of #582 which needs still needs mobile support

**Closed by KeeJef** 2020-02-21 00:09 UTC
